name: shop_bloc
description: "Shop BLoC."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Localization
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1

  # Local storage
  shared_preferences: ^2.0.17

  # BLoC
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  bloc_concurrency: ^0.2.3

  # Firebase
  cloud_firestore: ^4.15.8
  firebase_core: ^2.27.0
  firebase_analytics: ^10.8.9
  firebase_crashlytics: ^3.4.18

  # Auth
  firebase_auth: ^4.17.8

  one_day_auth:
    path: ../../Packages/dreambit-flutter-auth1

  # Core
  get_it: ^7.6.7
  auto_route: ^7.8.4
  dio: ^5.4.0
  pretty_dio_logger: ^1.3.1

  # Freezed
  freezed: ^2.4.7
  freezed_annotation: ^2.4.1

  # Utils
  meta: ^1.10.0
  stream_transform: ^2.1.0
  logger: ^2.0.2+1
  intl_utils: ^2.8.7
  url_strategy: ^0.2.0
  package_info_plus: ^5.0.1
  permission_handler: ^11.2.1

  # UI
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.8
  flutter_gen_runner: ^5.4.0

flutter:
  uses-material-design: true

  assets:
    - assets/svg/

flutter_gen:
  output: lib/core/assets/generated
  line_length: 80

flutter_intl:
  enabled: true
  class_name: AppLocalization
  main_locale: en
  arb_dir: lib/core/localization/translations
  output_dir: lib/core/localization/generated
