name: shop_bloc
description: "Shop BLoC."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Localization
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1

  # Local storage
  shared_preferences: ^2.0.17

  # BLoC
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  bloc_concurrency: ^0.2.3

  # Firebase
  firebase_core: ^2.25.4
#  firebase_messaging: ^14.7.16
  firebase_analytics: ^10.8.6
  firebase_crashlytics: ^3.4.15
#  firebase_dynamic_links: ^5.4.14

  # Auth
  firebase_auth: ^4.17.5

  firebase_ui_auth:
    git:
      url: https://github.com/alexandr-zherebtsov/FirebaseUI-Flutter.git
      path: packages/firebase_ui_auth/
      ref: feature/UI-builders
  firebase_ui_oauth_apple:
    git:
      url: https://github.com/alexandr-zherebtsov/FirebaseUI-Flutter.git
      path: packages/firebase_ui_oauth_apple/
      ref: feature/UI-builders
  firebase_ui_oauth_google:
    git:
      url: https://github.com/alexandr-zherebtsov/FirebaseUI-Flutter.git
      path: packages/firebase_ui_oauth_google/
      ref: feature/UI-builders
  firebase_ui_oauth_facebook:
    git:
      url: https://github.com/alexandr-zherebtsov/FirebaseUI-Flutter.git
      path: packages/firebase_ui_oauth_facebook/
      ref: feature/UI-builders
  firebase_ui_oauth_twitter:
    git:
      url: https://github.com/alexandr-zherebtsov/FirebaseUI-Flutter.git
      path: packages/firebase_ui_oauth_twitter/
      ref: feature/UI-builders

#  firebase_ui_auth:
#    path: packages/firebase_ui_auth/packages/firebase_ui_auth
#  firebase_ui_oauth_apple:
#    path: packages/firebase_ui_auth/packages/firebase_ui_oauth_apple
#  firebase_ui_oauth_google:
#    path: packages/firebase_ui_auth/packages/firebase_ui_oauth_google
#  firebase_ui_oauth_facebook:
#    path: packages/firebase_ui_auth/packages/firebase_ui_oauth_facebook
#  firebase_ui_oauth_twitter:
#    path: packages/firebase_ui_auth/packages/firebase_ui_oauth_twitter

# do not use

#  firebase_ui_auth: ^1.13.0
#  firebase_ui_oauth_apple: ^1.2.18
#  firebase_ui_oauth_google: ^1.3.0
#  firebase_ui_oauth_facebook: ^1.2.18
#  firebase_ui_oauth_twitter: ^1.2.18

#  firebase_ui_database:
#    path: packages/firebase_ui_auth/packages/firebase_ui_database
#  firebase_ui_firestore:
#    path: packages/firebase_ui_auth/packages/firebase_ui_firestore
#  firebase_ui_localizations:
#    path: packages/firebase_ui_auth/packages/firebase_ui_localizations
#  firebase_ui_oauth:
#    path: packages/firebase_ui_auth/packages/firebase_ui_oauth
#  firebase_ui_shared:
#    path: packages/firebase_ui_auth/packages/firebase_ui_shared
#  firebase_ui_storage:
#    path: packages/firebase_ui_auth/packages/firebase_ui_storage


  # Core
  get_it: ^7.6.7
  auto_route: ^7.8.4
  dio: ^5.4.0
  pretty_dio_logger: ^1.3.1

  # Freezed
  freezed: ^2.4.7
  freezed_annotation: ^2.4.1

  # Utils
  meta: ^1.10.0
  stream_transform: ^2.1.0
  logger: ^2.0.2+1
  intl_utils: ^2.8.7
  package_info_plus: ^5.0.1
  permission_handler: ^11.2.1

  # UI
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.8
  flutter_gen_runner: ^5.4.0

flutter:
  uses-material-design: true

  assets:
    - assets/svg/

  fonts:
    - family: SocialIcons
      fonts:
        - asset: packages/firebase_ui_auth/fonts/SocialIcons.ttf

flutter_gen:
  output: lib/core/assets/generated
  line_length: 80

flutter_intl:
  enabled: true
  class_name: AppLocalization
  main_locale: en
  arb_dir: lib/core/localization/translations
  output_dir: lib/core/localization/generated
